namespace TypeRacerServer.Core.Domain.Constant;

public static class GameQuotes
{
    public static readonly string[] Quotes = new[]
    {
        "public static void Main(string[] args) { Console.WriteLine(\"System Init\"); }",
        "var user = await db.Users.FirstOrDefaultAsync(u => u.Username == request.Username);",
        "public IEnumerable<int> GetNumbers() { yield return 1; }",
        "Task.Run(() => ProcessDataAsync(token)).Wait();",
        "[ApiController] [Route(\"api/[controller]\")] public class AuthController : ControllerBase { }",
        "private static ConcurrentDictionary<string, string> PlayerRooms = new();",
        "string newCid = Context.ConnectionId; var room = RoomManager.GetOrAdd(HostCode, _ => new RoomState());",
        "public async Task StartRoomGame(string HostCode) { room.GameStarted = true; }",
        "await Clients.Group(hostcode).SendAsync(\"UpdatePlayersList\", roomdata);",
        "if (DateTime.Now < freezeEnd) { return; } else { FrozenPlayers.TryRemove(cid, out _); }",
        "_ = Task.Run(async () => { await Task.Delay(15000); });",
        "bool isError = currentInput.Length > correctLength;",
        "int progressPercentage = (correctLength * 100) / targetText.Length;",
        "builder.Services.AddSignalR(); app.MapHub<GameHub>(\"/gamehub\");",
        "const hack = async (target) => { await sys.Bypass(target); return true; };",
        "document.getElementById(\"btn\").addEventListener(\"click\", () => alert(\"Hacked!\"));",
        "setTimeout(() => { console.log(\"Timeout finished\"); }, 1000);",
        "const [count, setCount] = useState(0); useEffect(() => { setCount(c => c + 1); }, []);",
        "import { HubConnectionBuilder } from '@microsoft/signalr';",
        "export const useGameLogic = () => { const [session, setSession] = useState(null); };",
        "const savedData = JSON.parse(localStorage.getItem('user_data')) || {};",
        "app.use((err, req, res, next) => { res.status(500).send('Server Error'); });",
        "const SECURE_KEY = crypto.createHash('sha256').update(pwd).digest('hex');",
        "SELECT * FROM Users WHERE clearance_level = 'TOP_SECRET' ORDER BY id DESC;",
        "UPDATE Players SET score = score + 100 WHERE username = 'admin';",
        "DELETE FROM system_logs WHERE date < NOW() - INTERVAL '7 days';",
        "INSERT INTO audit (event, ts) VALUES ('BREACH', CURRENT_TIMESTAMP);",
        "CREATE INDEX idx_user_email ON Users (email);",
        "def inject_payload(buffer): return buffer ^ 0xFF",
        "with open(\"config.json\", \"r\") as file: data = json.load(file)",
        "import numpy as np; arr = np.zeros((10, 10))",
        "@app.route('/api/v1/data', methods=['GET', 'POST'])",
        "class NeuralNet(nn.Module): def __init__(self): super().__init__()",
        "int main(int argc, char *argv[]) { return 0; }",
        "void* ptr = malloc(sizeof(int) * 100); free(ptr);",
        "std::cout << \"Segmentation fault (core dumped)\" << std::endl;",
        "for(int i=0; i<MAX_BUFFER; ++i) { buffer[i] = 0x00; }",
        "<div className=\"glass-panel\" style={{ textAlign: 'center' }}></div>",
        "body { background-color: var(--bg-main); font-family: 'Inter', sans-serif; }",
        "@keyframes glitch { 0% { transform: skewX(0deg); } 100% { transform: skewX(2deg); } }",
        "<input type=\"text\" className=\"cyber-input\" placeholder=\"ENTER CODE\" />",
        "chmod +x deploy.sh && ./deploy.sh --force",
        "ssh root@192.168.1.10 -p 2222 -i ~/.ssh/id_rsa",
        "tail -f /var/log/syslog | grep \"CRITICAL ERROR\"",
        "ping 127.0.0.1 -c 4 > /dev/null 2>&1",
        "curl -X POST http://localhost:5293/api/save-score -d '{\"Wpm\": 120}'",
        "tar -czvf backup.tar.gz /var/www/html/",
        "try { server.Overload(); } catch (Exception ex) { Protocol.InitiateWipe(); }",
        "if (enemy.Shields <= 0) { weapon.Fire(WeaponType.Laser); }",
        "sys.InitNetwork(); firewall.Bypass(Proxy.GenerateIP());",
        "void TriggerOverload() { core.Temp += 500; core.Melt(); }",
        "Connection.Intercept(); DataStream.Decrypt();"
    };
}